/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardenRouteImport } from './routes/warden'
import { Route as StudentRouteImport } from './routes/student'
import { Route as OrgAdminRouteImport } from './routes/org-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as DeptAdminRouteImport } from './routes/dept-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardenIndexRouteImport } from './routes/warden.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as OrgAdminIndexRouteImport } from './routes/org-admin.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as DeptAdminIndexRouteImport } from './routes/dept-admin.index'
import { Route as WardenVisitorsRouteImport } from './routes/warden.visitors'
import { Route as WardenRoomsRouteImport } from './routes/warden.rooms'
import { Route as WardenOutpassesRouteImport } from './routes/warden.outpasses'
import { Route as StudentHostelRouteImport } from './routes/student.hostel'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentChatRouteImport } from './routes/student.chat'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as OrgAdminVisitorsRouteImport } from './routes/org-admin.visitors'
import { Route as OrgAdminRoomsRouteImport } from './routes/org-admin.rooms'
import { Route as OrgAdminOutpassesRouteImport } from './routes/org-admin.outpasses'
import { Route as OrgAdminAnalyticsRouteImport } from './routes/org-admin.analytics'
import { Route as FacultyAttendanceRouteImport } from './routes/faculty.attendance'
import { Route as FacultyAssignmentsRouteImport } from './routes/faculty.assignments'
import { Route as DeptAdminStudentsRouteImport } from './routes/dept-admin.students'

const WardenRoute = WardenRouteImport.update({
  id: '/warden',
  path: '/warden',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAdminRoute = OrgAdminRouteImport.update({
  id: '/org-admin',
  path: '/org-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptAdminRoute = DeptAdminRouteImport.update({
  id: '/dept-admin',
  path: '/dept-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardenIndexRoute = WardenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WardenRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const OrgAdminIndexRoute = OrgAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgAdminRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const DeptAdminIndexRoute = DeptAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeptAdminRoute,
} as any)
const WardenVisitorsRoute = WardenVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => WardenRoute,
} as any)
const WardenRoomsRoute = WardenRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => WardenRoute,
} as any)
const WardenOutpassesRoute = WardenOutpassesRouteImport.update({
  id: '/outpasses',
  path: '/outpasses',
  getParentRoute: () => WardenRoute,
} as any)
const StudentHostelRoute = StudentHostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentChatRoute = StudentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const OrgAdminVisitorsRoute = OrgAdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminRoomsRoute = OrgAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminOutpassesRoute = OrgAdminOutpassesRouteImport.update({
  id: '/outpasses',
  path: '/outpasses',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminAnalyticsRoute = OrgAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OrgAdminRoute,
} as any)
const FacultyAttendanceRoute = FacultyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAssignmentsRoute = FacultyAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => FacultyRoute,
} as any)
const DeptAdminStudentsRoute = DeptAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DeptAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dept-admin': typeof DeptAdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/org-admin': typeof OrgAdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/warden': typeof WardenRouteWithChildren
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/org-admin/analytics': typeof OrgAdminAnalyticsRoute
  '/org-admin/outpasses': typeof OrgAdminOutpassesRoute
  '/org-admin/rooms': typeof OrgAdminRoomsRoute
  '/org-admin/visitors': typeof OrgAdminVisitorsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/chat': typeof StudentChatRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hostel': typeof StudentHostelRoute
  '/warden/outpasses': typeof WardenOutpassesRoute
  '/warden/rooms': typeof WardenRoomsRoute
  '/warden/visitors': typeof WardenVisitorsRoute
  '/dept-admin/': typeof DeptAdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/org-admin/': typeof OrgAdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/warden/': typeof WardenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/org-admin/analytics': typeof OrgAdminAnalyticsRoute
  '/org-admin/outpasses': typeof OrgAdminOutpassesRoute
  '/org-admin/rooms': typeof OrgAdminRoomsRoute
  '/org-admin/visitors': typeof OrgAdminVisitorsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/chat': typeof StudentChatRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hostel': typeof StudentHostelRoute
  '/warden/outpasses': typeof WardenOutpassesRoute
  '/warden/rooms': typeof WardenRoomsRoute
  '/warden/visitors': typeof WardenVisitorsRoute
  '/dept-admin': typeof DeptAdminIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/org-admin': typeof OrgAdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/warden': typeof WardenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dept-admin': typeof DeptAdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/login': typeof LoginRoute
  '/org-admin': typeof OrgAdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/warden': typeof WardenRouteWithChildren
  '/dept-admin/students': typeof DeptAdminStudentsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRoute
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/org-admin/analytics': typeof OrgAdminAnalyticsRoute
  '/org-admin/outpasses': typeof OrgAdminOutpassesRoute
  '/org-admin/rooms': typeof OrgAdminRoomsRoute
  '/org-admin/visitors': typeof OrgAdminVisitorsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/chat': typeof StudentChatRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/hostel': typeof StudentHostelRoute
  '/warden/outpasses': typeof WardenOutpassesRoute
  '/warden/rooms': typeof WardenRoomsRoute
  '/warden/visitors': typeof WardenVisitorsRoute
  '/dept-admin/': typeof DeptAdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/org-admin/': typeof OrgAdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/warden/': typeof WardenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dept-admin'
    | '/faculty'
    | '/login'
    | '/org-admin'
    | '/student'
    | '/warden'
    | '/dept-admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/org-admin/analytics'
    | '/org-admin/outpasses'
    | '/org-admin/rooms'
    | '/org-admin/visitors'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/chat'
    | '/student/fees'
    | '/student/hostel'
    | '/warden/outpasses'
    | '/warden/rooms'
    | '/warden/visitors'
    | '/dept-admin/'
    | '/faculty/'
    | '/org-admin/'
    | '/student/'
    | '/warden/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dept-admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/org-admin/analytics'
    | '/org-admin/outpasses'
    | '/org-admin/rooms'
    | '/org-admin/visitors'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/chat'
    | '/student/fees'
    | '/student/hostel'
    | '/warden/outpasses'
    | '/warden/rooms'
    | '/warden/visitors'
    | '/dept-admin'
    | '/faculty'
    | '/org-admin'
    | '/student'
    | '/warden'
  id:
    | '__root__'
    | '/'
    | '/dept-admin'
    | '/faculty'
    | '/login'
    | '/org-admin'
    | '/student'
    | '/warden'
    | '/dept-admin/students'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/org-admin/analytics'
    | '/org-admin/outpasses'
    | '/org-admin/rooms'
    | '/org-admin/visitors'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/certificates'
    | '/student/chat'
    | '/student/fees'
    | '/student/hostel'
    | '/warden/outpasses'
    | '/warden/rooms'
    | '/warden/visitors'
    | '/dept-admin/'
    | '/faculty/'
    | '/org-admin/'
    | '/student/'
    | '/warden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeptAdminRoute: typeof DeptAdminRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrgAdminRoute: typeof OrgAdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  WardenRoute: typeof WardenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warden': {
      id: '/warden'
      path: '/warden'
      fullPath: '/warden'
      preLoaderRoute: typeof WardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-admin': {
      id: '/org-admin'
      path: '/org-admin'
      fullPath: '/org-admin'
      preLoaderRoute: typeof OrgAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept-admin': {
      id: '/dept-admin'
      path: '/dept-admin'
      fullPath: '/dept-admin'
      preLoaderRoute: typeof DeptAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warden/': {
      id: '/warden/'
      path: '/'
      fullPath: '/warden/'
      preLoaderRoute: typeof WardenIndexRouteImport
      parentRoute: typeof WardenRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/org-admin/': {
      id: '/org-admin/'
      path: '/'
      fullPath: '/org-admin/'
      preLoaderRoute: typeof OrgAdminIndexRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/dept-admin/': {
      id: '/dept-admin/'
      path: '/'
      fullPath: '/dept-admin/'
      preLoaderRoute: typeof DeptAdminIndexRouteImport
      parentRoute: typeof DeptAdminRoute
    }
    '/warden/visitors': {
      id: '/warden/visitors'
      path: '/visitors'
      fullPath: '/warden/visitors'
      preLoaderRoute: typeof WardenVisitorsRouteImport
      parentRoute: typeof WardenRoute
    }
    '/warden/rooms': {
      id: '/warden/rooms'
      path: '/rooms'
      fullPath: '/warden/rooms'
      preLoaderRoute: typeof WardenRoomsRouteImport
      parentRoute: typeof WardenRoute
    }
    '/warden/outpasses': {
      id: '/warden/outpasses'
      path: '/outpasses'
      fullPath: '/warden/outpasses'
      preLoaderRoute: typeof WardenOutpassesRouteImport
      parentRoute: typeof WardenRoute
    }
    '/student/hostel': {
      id: '/student/hostel'
      path: '/hostel'
      fullPath: '/student/hostel'
      preLoaderRoute: typeof StudentHostelRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/chat': {
      id: '/student/chat'
      path: '/chat'
      fullPath: '/student/chat'
      preLoaderRoute: typeof StudentChatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/org-admin/visitors': {
      id: '/org-admin/visitors'
      path: '/visitors'
      fullPath: '/org-admin/visitors'
      preLoaderRoute: typeof OrgAdminVisitorsRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/rooms': {
      id: '/org-admin/rooms'
      path: '/rooms'
      fullPath: '/org-admin/rooms'
      preLoaderRoute: typeof OrgAdminRoomsRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/outpasses': {
      id: '/org-admin/outpasses'
      path: '/outpasses'
      fullPath: '/org-admin/outpasses'
      preLoaderRoute: typeof OrgAdminOutpassesRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/org-admin/analytics': {
      id: '/org-admin/analytics'
      path: '/analytics'
      fullPath: '/org-admin/analytics'
      preLoaderRoute: typeof OrgAdminAnalyticsRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/faculty/attendance': {
      id: '/faculty/attendance'
      path: '/attendance'
      fullPath: '/faculty/attendance'
      preLoaderRoute: typeof FacultyAttendanceRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/assignments': {
      id: '/faculty/assignments'
      path: '/assignments'
      fullPath: '/faculty/assignments'
      preLoaderRoute: typeof FacultyAssignmentsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/dept-admin/students': {
      id: '/dept-admin/students'
      path: '/students'
      fullPath: '/dept-admin/students'
      preLoaderRoute: typeof DeptAdminStudentsRouteImport
      parentRoute: typeof DeptAdminRoute
    }
  }
}

interface DeptAdminRouteChildren {
  DeptAdminStudentsRoute: typeof DeptAdminStudentsRoute
  DeptAdminIndexRoute: typeof DeptAdminIndexRoute
}

const DeptAdminRouteChildren: DeptAdminRouteChildren = {
  DeptAdminStudentsRoute: DeptAdminStudentsRoute,
  DeptAdminIndexRoute: DeptAdminIndexRoute,
}

const DeptAdminRouteWithChildren = DeptAdminRoute._addFileChildren(
  DeptAdminRouteChildren,
)

interface FacultyRouteChildren {
  FacultyAssignmentsRoute: typeof FacultyAssignmentsRoute
  FacultyAttendanceRoute: typeof FacultyAttendanceRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyAssignmentsRoute: FacultyAssignmentsRoute,
  FacultyAttendanceRoute: FacultyAttendanceRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface OrgAdminRouteChildren {
  OrgAdminAnalyticsRoute: typeof OrgAdminAnalyticsRoute
  OrgAdminOutpassesRoute: typeof OrgAdminOutpassesRoute
  OrgAdminRoomsRoute: typeof OrgAdminRoomsRoute
  OrgAdminVisitorsRoute: typeof OrgAdminVisitorsRoute
  OrgAdminIndexRoute: typeof OrgAdminIndexRoute
}

const OrgAdminRouteChildren: OrgAdminRouteChildren = {
  OrgAdminAnalyticsRoute: OrgAdminAnalyticsRoute,
  OrgAdminOutpassesRoute: OrgAdminOutpassesRoute,
  OrgAdminRoomsRoute: OrgAdminRoomsRoute,
  OrgAdminVisitorsRoute: OrgAdminVisitorsRoute,
  OrgAdminIndexRoute: OrgAdminIndexRoute,
}

const OrgAdminRouteWithChildren = OrgAdminRoute._addFileChildren(
  OrgAdminRouteChildren,
)

interface StudentRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentChatRoute: typeof StudentChatRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentHostelRoute: typeof StudentHostelRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentChatRoute: StudentChatRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentHostelRoute: StudentHostelRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface WardenRouteChildren {
  WardenOutpassesRoute: typeof WardenOutpassesRoute
  WardenRoomsRoute: typeof WardenRoomsRoute
  WardenVisitorsRoute: typeof WardenVisitorsRoute
  WardenIndexRoute: typeof WardenIndexRoute
}

const WardenRouteChildren: WardenRouteChildren = {
  WardenOutpassesRoute: WardenOutpassesRoute,
  WardenRoomsRoute: WardenRoomsRoute,
  WardenVisitorsRoute: WardenVisitorsRoute,
  WardenIndexRoute: WardenIndexRoute,
}

const WardenRouteWithChildren =
  WardenRoute._addFileChildren(WardenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeptAdminRoute: DeptAdminRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  LoginRoute: LoginRoute,
  OrgAdminRoute: OrgAdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  WardenRoute: WardenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
